In [ ]:
import pandas as pd

In [34]:
import numpy as np

In [7]:
pd.__version__

'3.0.6'

In [4]:
df = pd.read_csv('https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/car_fuel_efficiency_2026.csv')

In [5]:
df.head()

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0

In [6]:
df.info

<bound method DataFrame.info of       model_year  origin fuel_type         drivetrain  num_doors  \
0           2006  Europe  Gasoline  Front-wheel drive          4
1           2008  Europe    Diesel  Front-wheel drive          4
2           1996    Asia  Gasoline  Front-wheel drive          5
3           1989  Europe  Gasoline  Front-wheel drive          4
4           1994     USA    Diesel  Front-wheel drive          3
...          ...     ...       ...                ...        ...
9995        2005     USA  Gasoline    All-wheel drive          4
9996        1993    Asia  Gasoline    All-wheel drive          2
9997        2014     USA  Gasoline    All-wheel drive          3
9998        2004     USA    Hybrid   Rear-wheel drive          5
9999        2011     USA    Diesel  Front-wheel drive          4

      engine_displacement  num_cylinders  horsepower  vehicle_weight  \
0                    2180              6       243.0            3870
1                    2390              6       272.0            4210
2                    2320              6       267.0            4240
3                    2130              6       258.0            4490
4                    2580              7       304.0            4510
...                   ...            ...         ...             ...
9995                 2470              6       271.0            4690
9996                 2300              6       244.0            4370
9997                 2480              6       267.0            4590
9998                 2180              6       270.0            4450
9999                 2380              6       295.0            4370

      acceleration  fuel_efficiency_mpg
0              NaN                 31.9
1              NaN                 31.3
2             17.3                 27.5
3             18.7                 28.5
4             17.5                 31.0
...            ...                  ...
9995          18.9                 27.4
9996          19.0                 30.0
9997          18.4                 28.1
9998          20.9                 32.2
9999          17.6                 30.2

[10000 rows x 11 columns]>

In [8]:
df.fuel_type

0       Gasoline
1         Diesel
2       Gasoline
3       Gasoline
4         Diesel
          ...
9995    Gasoline
9996    Gasoline
9997    Gasoline
9998      Hybrid
9999      Diesel
Name: fuel_type, Length: 10000, dtype: str

In [9]:
df.nunique()

model_year              50
origin                   3
fuel_type                3
drivetrain               3
num_doors                4
engine_displacement    127
num_cylinders            5
horsepower             153
vehicle_weight         176
acceleration            93
fuel_efficiency_mpg    188
dtype: int64

In [10]:
df.isnull().sum()

model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors                0
engine_displacement      0
num_cylinders            0
horsepower             877
vehicle_weight           0
acceleration           264
fuel_efficiency_mpg      0
dtype: int64

In [11]:
df["origin"].unique()

<StringArray>
['Europe', 'Asia', 'USA']
Length: 3, dtype: str

In [12]:
df[df["origin"] == "Asia"]

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
6,1992,Asia,Gasoline,Front-wheel drive,2,2270,6,250.0,4310,21.7,26.8
8,1997,Asia,Gasoline,Rear-wheel drive,3,2330,6,251.0,4230,19.5,30.9
10,1978,Asia,Gasoline,All-wheel drive,3,2410,6,NaN,4420,19.5,26.8
15,2007,Asia,Diesel,Front-wheel drive,4,2170,5,226.0,3950,18.0,35.4
...,...,...,...,...,...,...,...,...,...,...,...
9984,2011,Asia,Gasoline,Front-wheel drive,3,2410,6,256.0,4610,20.2,32.4
9987,2004,Asia,Diesel,All-wheel drive,3,2180,6,266.0,4530,18.6,29.0
9990,1975,Asia,Diesel,Front-wheel drive,4,1940,6,236.0,3630,19.7,32.4
9994,1993,Asia,Gasoline,Rear-wheel drive,2,2360,6,257.0,4610,22.2,30.1
9996,1993,Asia,Gasoline,All-wheel drive,2,2300,6,244.0,4370,19.0,30.0

In [13]:
df[df["origin"] == "Asia"]["fuel_efficiency_mpg"]

2       27.5
6       26.8
8       30.9
10      26.8
15      35.4
        ...
9984    32.4
9987    29.0
9990    32.4
9994    30.1
9996    30.0
Name: fuel_efficiency_mpg, Length: 2994, dtype: float64

In [14]:
df[df["origin"] == "Asia"]["fuel_efficiency_mpg"].max()

np.float64(41.2)

In [15]:
df.horsepower.median()

np.float64(254.0)

In [19]:
df.horsepower.value_counts()

horsepower
252.0    174
246.0    168
256.0    168
259.0    165
253.0    165
        ...
322.0      1
330.0      1
175.0      1
178.0      1
320.0      1
Name: count, Length: 153, dtype: int64

In [42]:
df["horsepower"] = df["horsepower"].fillna(252.0)

In [43]:
df.horsepower

0       243.0
1       272.0
2       267.0
3       258.0
4       304.0
        ...
9995    271.0
9996    244.0
9997    267.0
9998    270.0
9999    295.0
Name: horsepower, Length: 10000, dtype: float64

In [44]:
df["horsepower"].median()

np.float64(252.0)

In [24]:
df[df['origin'] == 'Asia'][["vehicle_weight", "model_year"]]

      vehicle_weight  model_year
2               4240        1996
6               4310        1992
8               4230        1997
10              4420        1978
15              3950        2007
...              ...         ...
9984            4610        2011
9987            4530        2004
9990            3630        1975
9994            4610        1993
9996            4370        1993

[2994 rows x 2 columns]

In [25]:
df[df['origin'] == 'Asia'][["vehicle_weight", "model_year"]].head(7)

    vehicle_weight  model_year
2             4240        1996
6             4310        1992
8             4230        1997
10            4420        1978
15            3950        2007
16            4750        2021
22            4450        2019

In [28]:
X = df[df['origin'] == 'Asia'][["vehicle_weight", "model_year"]].head(7).values

In [29]:
X

array([[4240, 1996],
       [4310, 1992],
       [4230, 1997],
       [4420, 1978],
       [3950, 2007],
       [4750, 2021],
       [4450, 2019]])

In [30]:
X_tra = X.T

In [31]:
X_tra

array([[4240, 4310, 4230, 4420, 3950, 4750, 4450],
       [1996, 1992, 1997, 1978, 2007, 2021, 2019]])

In [32]:
X_tra.dot(X)

array([[131950500,  60750580],
       [ 60750580,  28041424]])

In [33]:
XTX = X_tra.dot(X)

In [35]:
XTX_inv = np.linalg.inv(XTX)

In [36]:
XTX_inv

array([[ 2.96830537e-06, -6.43071025e-06],
       [-6.43071025e-06,  1.39675281e-05]])

In [37]:
XTX_inv @ XTX

array([[ 1.00000000e+00, -7.77917769e-15],
       [-8.75935812e-14,  1.00000000e+00]])

In [38]:
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])

In [39]:
w = XTX_inv @ X.T @ y

In [40]:
w

array([0.13644777, 0.2327492 ])

In [41]:
w.sum()

np.float64(0.36919696904925486)